#include <iostream>


using  namespace std;

int main()
{
	try
	{
		int a = 10;
	}
	catch(std::exception ex)
	{
	}
}